post_install() {
    if [ -d /run/systemd/system ]; then
        for u in kait2en-dgpu-off.service kait2en-dgpu-suspend.service kait2en-amdgpu-profile.service kait2en-amdgpu-profile-resume.service; do
            if systemctl is-active --quiet "$u"; then
                systemctl stop "$u"
            fi
            if systemctl is-enabled --quiet "$u"; then
                systemctl disable "$u"
            fi
        done
        systemctl daemon-reload
    fi
}

post_upgrade() {
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload
    fi
}

post_remove() {
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload
    fi
}
