###############################################
# arch-mact2-rankmirrors.conf
# A configuration file for arch-mact2-rankmirrors.
#
# Values are parsed by a Python script, but they look like shell variables.
###############################################

# T2LINUX_OVERWRITE_MIRRORLIST determines whether the
# new t2linux mirror list will automatically overwrite
# the existing list or simply be stored as a .pacnew file.
# Supported values:
#   "yes"     Overwrite the existing /etc/pacman.d/arch-mact2-mirrorlist.
#   "no"      Save new mirror list as a .pacnew file (default).
#
T2LINUX_OVERWRITE_MIRRORLIST="no"

# T2LINUX_AUTO_MIRROR_RANKING is an alias to T2LINUX_OVERWRITE_MIRRORLIST
# for backwards compatibility.
#
T2LINUX_AUTO_MIRROR_RANKING=$T2LINUX_OVERWRITE_MIRRORLIST

# T2LINUX_AUTORANK_TIMEOUT specifies the maximum time (in seconds)
# for each mirror to return the full answer.
#
T2LINUX_AUTORANK_TIMEOUT="30"

# ALWAYS_FIRST_T2LINUX_MIRRORS pre-determines the preferred mirrors in the ranking result.
# It contains a simple list of (partial) mirror names separated by pipe (|) characters.
# Examples:
#   ALWAYS_FIRST_T2LINUX_MIRRORS='github|funami'
#   ALWAYS_FIRST_T2LINUX_MIRRORS='https://mirror.funami.tech/arch-mact2/os/$arch'
#
ALWAYS_FIRST_T2LINUX_MIRRORS=""

# T2LINUX_IGNORED_MIRRORS is a list of (partial) mirror names to ignore.
# Same as the --ignore option. Separate by spaces or pipes.
#
T2LINUX_IGNORED_MIRRORS=""

# T2LINUX_RANKMIRRORS_EXIT_CODE_VERBOSITY specifies how much information will be shown when
# a mirror fails to rank. Supported values:
#     all     All available information
#     code    Less than above, including connection error code
#     show    Less than above, no connection error info
#     none    Nothing
# Default is "show".
#
T2LINUX_RANKMIRRORS_EXIT_CODE_VERBOSITY="show"

# T2LINUX_RANK_WHEN_MIRRORLIST_CHANGES specifies whether to automatically run arch-mact2-rankmirrors
# when package 'arch-mact2-mirrorlist' gets an update.
# Supported values:
#    yes       (default)
#    no
#
T2LINUX_RANK_WHEN_MIRRORLIST_CHANGES="yes"

# T2LINUX_KEEP_UNRANKED_LIST_BY_HOOK is used when the following two conditions hold:
#   - package arch-mact2-mirrorlist is just installed or updated
#   - if T2LINUX_RANK_WHEN_MIRRORLIST_CHANGES is set to "no"
# File /etc/pacman.d/arch-mact2-mirrorlist.pacnew will be deleted if
# T2LINUX_KEEP_UNRANKED_LIST_BY_HOOK is set to 'no'
# Supported values:
#    yes
#    no   (default)
#
T2LINUX_KEEP_UNRANKED_LIST_BY_HOOK="no"

# T2LINUX_SHOW_ORIGINAL_MIRRORLIST determines whether to include the original unranked
# list of mirrors to the end of the ranked file.
# Supported values:
#    yes  (default)
#    no
#
T2LINUX_SHOW_ORIGINAL_MIRRORLIST="yes"
